### PR TITLE
Include django jwt verifying key

### PR DESCRIPTION
**Pull request by catchysong**
Added jwt verifying key secret for prod environments (members and portunus use this value)

### CODE REVIEW

**Review by Ian-MacLeod — APPROVED** [review]
Lgtm, looks like the test failure is unrelated?

**Comment by catchysong** [comment]
Yeah I'm not sure why the backend linting is complaining about No container found for backend_1

**Comment by markrawls** [comment]
"No container found" means it crashed on startup, which is typically indicative of a problem in the settings file of the generated application.

**Comment by catchysong** [comment]
Closing because no longer needed. I will move the secrets manager related logic over to the django-willing-zg reop

**Pull request closed without merging**
